// Generated by gse_generate.py — DO NOT EDIT
// GSE-One version: 0.23.0
// Reproduces hooks/hooks.claude.json guardrails as a native opencode plugin.
import type { Plugin } from "@opencode-ai/plugin"
import { $ } from "bun"

export const GseGuardrails: Plugin = async () => {
  return {
    "tool.execute.before": async (input: any, output: any) => {
      if (input?.tool !== "bash") return
      const cmd = String(output?.args?.command ?? "")

      if (cmd.startsWith("git push --force")) {
        throw new Error(
          "EMERGENCY GUARDRAIL: Force push detected. This can cause permanent data loss. Aborting."
        )
      }

      if (cmd.startsWith("git commit")) {
        const branch = (await $`git branch --show-current`.text()).trim()
        if (branch === "main") {
          throw new Error(
            "GUARDRAIL: Direct commit to main detected. Use a feature branch."
          )
        }
      }
    },

    "tool.execute.after": async (input: any, _output: any) => {
      if (input?.tool !== "bash") return
      const cmd = String(input?.args?.command ?? "")
      if (!cmd.startsWith("git push")) return

      try {
        const status = await Bun.file(".gse/status.yaml").text()
        const m = status.match(/review_findings_open:\s*(\d+)/)
        const open = m ? parseInt(m[1], 10) : 0
        if (open > 0) {
          console.warn(`WARNING: ${open} open review findings`)
        }
      } catch {
        // .gse/status.yaml absent — nothing to report
      }
    },
  }
}

export default GseGuardrails
