// Generated by gse_generate.py — DO NOT EDIT
// GSE-One version: 0.38.1
// Reproduces hooks/hooks.claude.json guardrails as a native opencode plugin.
import type { Plugin } from "@opencode-ai/plugin"
import { $ } from "bun"

export const GseGuardrails: Plugin = async () => {
  return {
    "tool.execute.before": async (input: any, output: any) => {
      if (input?.tool !== "bash") return
      const cmd = String(output?.args?.command ?? "")

      if (cmd.startsWith("git push --force")) {
        throw new Error(
          "EMERGENCY GUARDRAIL: Force push detected. This can cause permanent data loss. Aborting."
        )
      }

      if (cmd.startsWith("git commit")) {
        const branch = (await $`git branch --show-current`.text()).trim()
        if (branch === "main") {
          throw new Error(
            "GUARDRAIL: Direct commit to main detected. Use a feature branch."
          )
        }
      }
    },

    "tool.execute.after": async (input: any, _output: any) => {
      // Bash / git push — open review findings warning
      if (input?.tool === "bash") {
        const cmd = String(input?.args?.command ?? "")
        if (cmd.startsWith("git push")) {
          try {
            const status = await Bun.file(".gse/status.yaml").text()
            const m = status.match(/review_findings_open:\s*(\d+)/)
            const open = m ? parseInt(m[1], 10) : 0
            if (open > 0) {
              console.warn(`WARNING: ${open} open review findings`)
            }
          } catch {
            // .gse/status.yaml absent — nothing to report
          }
        }
        return
      }

      // Dashboard sync — fire on edit/write/multiedit (AMÉL-02).
      // Mirrors the PostToolUse hooks in hooks.claude.json / hooks.cursor.json,
      // including the double-defense error marker on subprocess failure.
      const toolName = String(input?.tool ?? "").toLowerCase()
      if (["edit", "write", "multiedit"].includes(toolName)) {
        try {
          const home = process.env.HOME ?? ""
          const registryPath = `${home}/.gse-one`
          const registryFile = Bun.file(registryPath)
          if (!(await registryFile.exists())) return
          const pluginPath = (await registryFile.text()).trim()
          if (!pluginPath) return
          const tool = `${pluginPath}/tools/dashboard.py`
          if (!(await Bun.file(tool).exists())) return
          const result = await $`python3 ${tool} --if-stale`.nothrow().quiet()
          if (result.exitCode !== 0) {
            // Double-defense: dashboard.py crashed before its own try/except ran
            const now = new Date().toISOString().replace(/\.\d+Z$/, "Z")
            const stderr = result.stderr?.toString() ?? "(no stderr)"
            const msg = JSON.stringify(`dashboard.py exited with code ${result.exitCode}`)
            const indented = stderr.split("\n").map((l: string) => `  ${l}`).join("\n")
            const content =
              `timestamp: "${now}"\n` +
              `message: ${msg}\n` +
              `traceback: |\n${indented}\n`
            try {
              await Bun.write(".gse/.dashboard-error.yaml", content)
            } catch { /* best-effort */ }
          }
        } catch {
          // Hook wrapper must never block the edit
        }
      }
    },
  }
}

export default GseGuardrails
